# Generated by Django 4.2.4 on 2024-06-26 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amar_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('total_bank_balance', models.IntegerField(default=Decimal('122000.00'))),
            ],
        ),
    ]
