# Generated by Django 4.2.4 on 2024-06-26 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amar_bank',
            name='bank_name',
            field=models.CharField(default='Amar Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='amar_bank',
            name='total_bank_balance',
            field=models.IntegerField(default={'balance__sum': Decimal('122100.00')}),
        ),
    ]
