# Generated by Django 4.2.4 on 2024-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_amar_bank_total_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amar_bank',
            name='total_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
