# Generated by Django 4.2.4 on 2024-06-29 20:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_amar_bank_total_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amar_bank',
            name='total_bank_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12),
        ),
    ]
