# Generated by Django 4.2.4 on 2024-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='ballance',
            new_name='balance',
        ),
    ]
